# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tetsuya/remote.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "tetsuya/remote.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14tetsuya/remote.proto\x12\x07tetsuya"\r\n\x0bListRequest"\x19\n\tListReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t"8\n\nRunRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x66orce\x18\x02 \x01(\x08\x12\r\n\x05\x63\x61\x63he\x18\x03 \x01(\x08"\x17\n\x08RunReply\x12\x0b\n\x03out\x18\x01 \x01(\t"\x0e\n\x0cTouchRequest"\x1a\n\nTouchReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2j\n\x07Service\x12\x30\n\x04List\x12\x14.tetsuya.ListRequest\x1a\x12.tetsuya.ListReply\x12-\n\x03Run\x12\x13.tetsuya.RunRequest\x1a\x11.tetsuya.RunReply2=\n\x06\x43onfig\x12\x33\n\x05Touch\x12\x15.tetsuya.TouchRequest\x1a\x13.tetsuya.TouchReplyb\x06proto3',
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tetsuya.remote_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LISTREQUEST"]._serialized_start = 33
    _globals["_LISTREQUEST"]._serialized_end = 46
    _globals["_LISTREPLY"]._serialized_start = 48
    _globals["_LISTREPLY"]._serialized_end = 73
    _globals["_RUNREQUEST"]._serialized_start = 75
    _globals["_RUNREQUEST"]._serialized_end = 131
    _globals["_RUNREPLY"]._serialized_start = 133
    _globals["_RUNREPLY"]._serialized_end = 156
    _globals["_TOUCHREQUEST"]._serialized_start = 158
    _globals["_TOUCHREQUEST"]._serialized_end = 172
    _globals["_TOUCHREPLY"]._serialized_start = 174
    _globals["_TOUCHREPLY"]._serialized_end = 200
    _globals["_SERVICE"]._serialized_start = 202
    _globals["_SERVICE"]._serialized_end = 308
    _globals["_CONFIG"]._serialized_start = 310
    _globals["_CONFIG"]._serialized_end = 371
# @@protoc_insertion_point(module_scope)
